######################################################
# https://github.com/nodejs/docker-node/blob/master/6/alpine/Dockerfile
# https://hub.docker.com/_/node/
######################################################

# Dockerfile for new core ui

FROM node:6-alpine


#RUN set -x && \
#  npm install -g webpack && \
#  npm install -g webpack-dev-server --save-dev && \
#  npm cache clean

#RUN set -x && \
#  cd /frontend && \
#  npm install && \
#  npm install -g webpack && \
#  webpack && \
#  npm cache clean


ADD . /frontend

## 设置alpine linux 阿里云源
RUN cp /etc/apk/repositories /etc/apk/repositories.bak
RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main" > /etc/apk/repositories
RUN echo "http://mirrors.aliyun.com/alpine/v3.4/community" >> /etc/apk/repositories

RUN set -x && \
  npm install -g cnpm --registry=https://registry.npm.taobao.org && \
  cd /frontend && \
  ls -l && \
  cnpm install -d && \
  cnpm run build && \
  npm cache clean


#  npm prune --production && \
  # You can even use npm prune without the --production flag

EXPOSE 9000

CMD ["cnpm", "run", "start"]
