export const customerConstants = {
	// get all
	CUSTOMER_GETALL_REQUEST: 'CUSTOMER_GETALL_REQUEST',
	CUSTOMER_GETALL_SUCCESS: 'CUSTOMER_GETALL_SUCCESS',
	CUSTOMER_GETALL_FAILURE: 'CUSTOMER_GETALL_FAILURE',
	// detail
	CUSTOMER_DETAIL_REQUEST: 'CUSTOMER_DETAIL_REQUEST',
	CUSTOMER_DETAIL_SUCCESS: 'CUSTOMER_DETAIL_SUCCESS',
	CUSTOMER_DETAIL_FAILURE: 'CUSTOMER_DETAIL_FAILURE',
	// programme list
	CUSTOMER_PROGRAMME_REQUEST: 'CUSTOMER_PROGRAMME_REQUEST',
	CUSTOMER_PROGRAMME_SUCCESS: 'CUSTOMER_PROGRAMME_SUCCESS',
	CUSTOMER_PROGRAMME_FAILURE: 'CUSTOMER_PROGRAMME_FAILURE',
	// activity
	CUSTOMER_ACTIVITY_REQUEST: 'CUSTOMER_ACTIVITY_REQUEST',
	CUSTOMER_ACTIVITY_SUCCESS: 'CUSTOMER_ACTIVITY_SUCCESS',
	CUSTOMER_ACTIVITY_FAILURE: 'CUSTOMER_ACTIVITY_FAILURE',
	// RewardSummary
	CUSTOMER_REWARDSUMMARY_REQUEST: 'CUSTOMER_REWARDSUMMARY_REQUEST',
	CUSTOMER_REWARDSUMMARY_SUCCESS: 'CUSTOMER_REWARDSUMMARY_SUCCESS',
	CUSTOMER_REWARDSUMMARY_FAILURE: 'CUSTOMER_REWARDSUMMARY_FAILURE'
};
