export const goodMasterConstants = {
	// get by types
	GOODMASTER_TYPES_REQUEST: 'GOODMASTER_TYPES_REQUEST',
	GOODMASTER_TYPES_SUCCESS: 'GOODMASTER_TYPES_SUCCESS',
	GOODMASTER_TYPES_FAILURE: 'GOODMASTER_TYPES_FAILURE'
};
