export const goodConstants = {
	// get by code
	GOOD_BY_CODE_REQUEST: 'GOOD_BY_CODE_REQUEST',
	GOOD_BY_CODE_SUCCESS: 'GOOD_BY_CODE_SUCCESS',
	GOOD_BY_CODE_FAILURE: 'GOOD_BY_CODE_FAILURE',
	// get AGGREGATION goods
	GOOD_AGGREGATION_REQUEST: 'GOOD_AGGREGATION_REQUEST',
	GOOD_AGGREGATION_SUCCESS: 'GOOD_AGGREGATION_SUCCESS',
	GOOD_AGGREGATION_FAILURE: 'GOOD_AGGREGATION_FAILURE'
};
