export const operationEventConstants = {
	// get all
	OPERATION_ALL_REQUEST: 'OPERATION_ALL_REQUEST',
	OPERATION_ALL_SUCCESS: 'OPERATION_ALL_SUCCESS',
	OPERATION_ALL_FAILURE: 'OPERATION_ALL_FAILURE'
};
