export const programmeConstants = {
	// get all
	PROGRAMME_GETALL_REQUEST: 'PROGRAMME_GETALL_REQUEST',
	PROGRAMME_GETALL_SUCCESS: 'PROGRAMME_GETALL_SUCCESS',
	PROGRAMME_GETALL_FAILURE: 'PROGRAMME_GETALL_FAILURE',
	// get ACTIVITY
	PROGRAMME_ACTIVITY_REQUEST: 'PROGRAMME_ACTIVITY_REQUEST',
	PROGRAMME_ACTIVITY_SUCCESS: 'PROGRAMME_ACTIVITY_SUCCESS',
	PROGRAMME_ACTIVITY_FAILURE: 'PROGRAMME_ACTIVITY_FAILURE'
};
