export const userConstants = {
	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	LOGOUT: 'USERS_LOGOUT',

	// language
	LANGUAGE_REQUEST: 'LANGUAGE_REQUEST',
	LANGUAGE_SUCCESS: 'LANGUAGE_SUCCESS',
	LANGUAGE_FAILURE: 'LANGUAGE_FAILURE',
	// user
	USER_REQUEST: 'USER_REQUEST',
	USER_SUCCESS: 'USER_SUCCESS',
	USER_FAILURE: 'USER_FAILURE'
};
